import { Link } from "react-router-dom";
import LegalLayout, { Section } from "@/components/LegalLayout";

export default function Terms() {
  return (
    <LegalLayout title="Terms of Service">
      <Section title="Using Debug">
        <p>
          Debug helps competitive programmers find failing test cases by comparing their code against a reference solution using AI and code execution.
          By creating an account you agree to these terms and to our <Link to="/privacy" className="text-primary hover:underline">Privacy Policy</Link>.
        </p>
      </Section>

      <Section title="Your account">
        <ul>
          <li>Keep your sign-in details safe; you are responsible for activity on your account.</li>
          <li>One person per account. Do not create accounts to get around plan limits.</li>
        </ul>
      </Section>

      <Section title="Your code">
        <ul>
          <li>You keep ownership of the code you submit.</li>
          <li>You allow us to process it (send it to AI providers and the code-execution service) only to provide the service.</li>
          <li>Only submit code you have the right to share. Do not submit secrets, passwords or personal data inside your code.</li>
          <li>Runs and their chats are deleted automatically after 3 months, so keep your own copies of anything important.</li>
        </ul>
      </Section>

      <Section title="Acceptable use">
        <p>Do not use the service to run malicious code, attack or overload the system, bypass limits, or break any law or contest rules.</p>
      </Section>

      <Section title="AI results">
        <p>
          Test cases, diagnoses and chat answers are generated by AI and may be wrong or incomplete. Always check them yourself. Do not rely on them as a guarantee your solution is correct.
        </p>
      </Section>

      <Section title="Plans and payments">
        <ul>
          <li>Free and paid plans have the limits shown on the Plans page. Only runs that finish are counted.</li>
          <li>Paid plans are one-time payments for 30 days, processed by Razorpay in INR. They do not renew automatically.</li>
          <li>When a paid period ends, the account returns to the Free plan.</li>
          <li>Cancelling stops nothing early — your plan stays active until its end date.</li>
          <li>Payments are generally non-refundable, except where required by law or in case of a billing error. Contact <a href="mailto:founders@debugcp.me" className="text-primary hover:underline">founders@debugcp.me</a> if you were charged incorrectly.</li>
        </ul>
      </Section>

      <Section title="Availability">
        <p>The service is provided "as is". It depends on third-party services and may be unavailable or change at times. We may update plans or features with notice on the site.</p>
      </Section>

      <Section title="Liability">
        <p>To the extent permitted by law, we are not liable for indirect losses, lost contest results, or data loss. Our total liability is limited to the amount you paid us in the last 30 days.</p>
      </Section>

      <Section title="Ending your account">
        <p>You can stop using the service at any time and ask us to delete your account by emailing <a href="mailto:founders@debugcp.me" className="text-primary hover:underline">founders@debugcp.me</a>. We may suspend accounts that break these terms.</p>
      </Section>

      <Section title="Governing law">
        <p>These terms are governed by the laws of India.</p>
      </Section>

      <Section title="Changes">
        <p>We may update these terms; the date at the top shows the latest version. Continuing to use the service means you accept the updated terms.</p>
      </Section>
    </LegalLayout>
  );
}
